name: Authenticator
main: com.stefthedev.authenticator.Authenticator
version: RELEASE-1.1
author: StefTheDev

commands:
  authenticator:
    description: The authentication plugin.
    aliases:
      - auth
      - authentication